# Primer on linear algebra in Numpy

## Instructions:
* Go through the notebook and complete the tasks. 
* Make sure you understand the examples given. If you need help, refer to the Essential readings or the documentation link provided, or go to the discussion forum. 
* When a question allows a free-form answer (e.g. what do you observe?), create a new markdown cell below and answer the question in the notebook. 
* Save your notebooks when you are done.
 
**Task 1:**
Go through the tutorial on Linear Algebra in Python here: http://ml-cheatsheet.readthedocs.io/en/latest/linear_algebra.html.
Paste and run the code from the tutorial in the empty cell below (or create new empty cells below) to get more familiar with the material.


In [1]:
import numpy as np

#Code here - use code samples from link above

**Task 2:**
Create the following matrices:

$X=\begin{bmatrix} 2 & 3 & 4 \\ 1 & 2 &3 \end{bmatrix},Y=\begin{bmatrix} 0 & 1 & 0 \\ 1 & 0 &0\\ 0 & 0 & 1 \end{bmatrix}$ 

Then do the following:
1.	Multiply ```X``` with ```Y``` (```Z1=X*Y=XY```) and print the result. What do you observe? 
2.	Multiply ```X``` with ```Y``` transpose (```Z2=X*Y.T```) and print the result. What do you observe? 
3.	What can you tell about matrix ```Y```, given ```Z1``` and ```Z2```? 

In [6]:
X = np.array([
 [2, 3, 4],
 [1, 2, 3]
 ])
X.shape == (2,3)
Y = np.array([
 [0, 1, 0],
 [1, 0, 0],
 [0, 0, 1]
 ])
Y.shape == (3,3)

Z1 = np.dot(X,Y)
print(Z1)

Z2 = np.dot(X,np.transpose(Y))
print(Z2)

[[3 2 4]
 [2 1 3]]
[[3 2 4]
 [2 1 3]]


**Task 3:** 
Create a 2x2 identity matrix ```I``` using the NumPy function ```eye(dim)``` $$ I=\begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix} $$


In [12]:
I = np.eye(2,dtype=int)
print(I)

[[1 0]
 [0 1]]


**Task 4:** 
1. Multiply (using dot) matrix ```I``` with the vector ```x``` defined below: $$Ix$$
2. Print the output.
3. What do you observe? 



In [13]:
x=np.array([2,3])
np.dot(x,I)

array([2, 3])

**Task 5:**
1.	Multiply (using dot) matrix ```I``` with the vector ```x``` defined below: $$Ix$$
2.	Print the output.
3.	What do you observe? 


In [16]:
X=np.array([[2,3],[4,5]])
np.dot(X,I)
#Code here

array([[2, 3],
       [4, 5]])

**Task 6:**
1. Multiply (using dot) matrix $X$ with the inverse matrix, $X^{-1}$ (use the NumPy function ```linalg.inv``` to do so): $XX^{-1}$
2. What do you observe? 




In [18]:
X=np.array([[1,2],[0,1]])
np.dot(X,np.linalg.inv(X))

array([[1., 0.],
       [0., 1.]])